build:
	coffee --bare --join dist.js --compile \
		src/ti.coffee \
		src/app/index.coffee \
		src/app/properties.coffee \
		src/platform/index.coffee \
		src/ui/index.coffee \
		src/ui/views/base.coffee \
		src/ui/iphone/index.coffee \
		src/ui/views/button.coffee \
		src/ui/views/label.coffee \
		src/ui/views/scroll_view.coffee \
		src/ui/views/search_bar.coffee \
		src/ui/views/tab_group.coffee \
		src/ui/views/table.coffee \
		src/ui/views/text_area.coffee \
		src/ui/views/text_field.coffee \
		src/ui/views/web_view.coffee \
		src/ui/views/window.coffee \
		src/ui/iphone/navigation_group.coffee \
		src/geolocation/index.coffee \
		src/map/index.coffee \
		src/map/view.coffee

.PHONY: build